import { IconType } from "react-icons";
import {
    SiHtml5,
    SiCss3,
    SiTailwindcss,
    SiJavascript,
    SiTypescript,
    SiReact,
    SiNextdotjs,
    SiNodedotjs,
    SiExpress,
    SiMongodb,
    SiPostgresql,
    SiFirebase,
    SiSupabase,
    SiGraphql,
    SiRedux,
    SiFigma,
    SiMui,
    SiGithub,
    SiJest,
    SiWebpack,
    SiVite,
    SiPrisma,
    SiKubernetes,
    SiLinux,
    SiNginx,
    SiPandas,
    SiTensorflow,
    SiDjango,
    SiCplusplus,
    SiC,
    SiKotlin,
} from "react-icons/si";
import { FaPython, FaDocker, FaGitAlt, FaJava } from "react-icons/fa";
import {
    IoLogoAndroid,
    IoLogoApple,
} from "react-icons/io";

export type Skill = {
    id: number;
    title: string;
    icon: IconType;
    color: string;
    category: string;
    description: string;
};

export const skills: Skill[] = [
   {
        id: 1,
        title: "Python",
        icon: FaPython,
        color: "#3776AB",
        category: "programming language",
        description: "A versatile programming language for various applications.",
    },
     {
        id: 2,
        title: "C",
        icon: SiC,
        color: "#A8B9CC",
        category: "programming language",
        description: "A general-purpose, procedural computer programming language.",
    },
    {
        id: 3,
        title: "C++",
        icon: SiCplusplus,
        color: "#00599C",
        category: "programming language",
        description: "A cross-platform programming language.",
    },
        {
        id: 4,
        title: "Java",
        icon: FaJava,
        color: "#007396",
        category: "programming language",
        description: "A high-level, class-based, object-oriented programming language.",
    },
    {
        id: 5,
        title: "Kotlin",
        icon: SiKotlin,
        color: "#A97BFF",
        category: "programming language",
        description: "A cross-platform, statically typed, general-purpose programming language with type inference.",
    },
    {
        id: 6,
        title: "HTML5",
        icon: SiHtml5,
        color: "#E34F26",
        category: "frontend",
        description: "The standard markup language for web pages.",
    },
    {
        id: 7,
        title: "CSS3",
        icon: SiCss3,
        color: "#1572B6",
        category: "frontend",
        description: "A style sheet language for describing the presentation of documents.",
    },
    {
        id: 8,
        title: "Tailwind CSS",
        icon: SiTailwindcss,
        color: "#06B6D4",
        category: "frontend",
        description: "A utility-first CSS framework for rapidly building custom designs.",
    },
    {
        id: 9,
        title: "JavaScript",
        icon: SiJavascript,
        color: "#F7DF1E",
        category: "frontend",
        description: "A programming language for the web.",
    },
    {
        id: 10,
        title: "TypeScript",
        icon: SiTypescript,
        color: "#3178C6",
        category: "frontend",
        description: "A strongly typed programming language that builds on JavaScript.",
    },
    {
        id: 11,
        title: "React",
        icon: SiReact,
        color: "#61DAFB",
        category: "frontend",
        description: "A JavaScript library for building user interfaces.",
    },
    {
        id: 12,
        title: "Next.js",
        icon: SiNextdotjs,
        color: "#000000",
        category: "frontend",
        description: "A React framework for production-grade applications.",
    },
    {
        id: 13,
        title: "Node.js",
        icon: SiNodedotjs,
        color: "#339933",
        category: "backend",
        description: "A JavaScript runtime built on Chrome's V8 engine.",
    },
    {
        id: 14,
        title: "MongoDB",
        icon: SiMongodb,
        color: "#47A248",
        category: "database",
        description: "A NoSQL database for modern applications.",
    },
    {
        id: 15,
        title: "PostgreSQL",
        icon: SiPostgresql,
        color: "#336791",
        category: "database",
        description: "An open-source relational database system.",
    },
    {
        id: 16,
        title: "Firebase",
        icon: SiFirebase,
        color: "#FFCA28",
        category: "database",
        description: "A platform for building mobile and web applications.",
    },
    {
        id: 17,
        title: "GraphQL",
        icon: SiGraphql,
        color: "#E10098",
        category: "backend",
        description: "A query language for APIs.",
    },
    {
        id: 18,
        title: "Git",
        icon: FaGitAlt,
        color: "#F05032",
        category: "tools",
        description: "A distributed version control system.",
    },
    {
        id: 19,
        title: "GitHub",
        icon: SiGithub,
        color: "#181717",
        category: "tools",
        description: "A platform for hosting and collaborating on code repositories.",
    },
    {
        id: 20,
        title: "Figma",
        icon: SiFigma,
        color: "#F24E1E",
        category: "tools",
        description: "A collaborative interface design tool.",
    },
    {
        id: 21,
        title: "Docker",
        icon: FaDocker,
        color: "#2496ED",
        category: "tools",
        description: "A platform for containerizing applications.",
    },
    {
        id: 22,
        title: "Webpack",
        icon: SiWebpack,
        color: "#8DD6F9",
        category: "frontend",
        description: "A static module bundler for JavaScript.",
    },
    {
        id: 23,
        title: "Vite",
        icon: SiVite,
        color: "#646CFF",
        category: "frontend",
        description: "A fast development build tool.",
    },
    {
        id: 24,
        title: "Prisma",
        icon: SiPrisma,
        color: "#2D3748",
        category: "backend",
        description: "A next-generation ORM for Node.js.",
    },
    {
        id: 25,
        title: "Linux",
        icon: SiLinux,
        color: "#FCC624",
        category: "tools",
        description: "An open-source operating system.",
    },
        {
        id: 26,
        title: "Pandas",
        icon: SiPandas,
        color: "#150458",
        category: "tools",
        description: "A data analysis library for Python.",
    },
    {
        id: 27,
        title: "TensorFlow",
        icon: SiTensorflow,
        color: "#FF6F00",
        category: "machine learning",
        description: "A machine learning framework by Google.",
    },
    {
        id: 28,
        title: "Android",
        icon: IoLogoAndroid,
        color: "#3DDC84",
        category: "mobile",
        description: "Mobile operating system developed by Google.",
    },
    {
        id: 29,
        title: "iOS",
        icon: IoLogoApple,
        color: "#A4A4A4",
        category: "mobile",
        description: "Mobile operating system developed by Apple.",
    },
];
